server:
# Source: HaGeZi Spam TLDs
# Updated: 01/04/2026  0:21:53,04
local-zone: "Package size exceeded the configured limit of 150 MB. Try https://github.com/hagezi/dns-blocklists/tree/37522026.90.38085/wildcard/spam-tlds-onlydomains.txt instead.." always_nxdomain
