#!/bin/bash

BLOCKLIST_DIR="/etc/unbound/unbound.conf.d/malware/devhunter"
WHITELIST_FILE="/etc/unbound/unbound.conf.d/zzz-whitelist/zzzzz-whitelist.conf"
WHITELIST_FILE="/etc/unbound/unbound.conf.d/malware/zzzz-whitelist/zzzz-hagezi-referral.conf"
WHITELIST_FILE="/etc/unbound/unbound.conf.d/malware/zzzz-whitelist/zzzz-shadowwhisperer-whitelist.conf"

echo "📊 Hitung domain Unbound"
echo

BLOCKLIST_DOMAINS=$(grep -Rh '^local-' "$BLOCKLIST_DIR" | awk '{print $2}' | tr -d '"' | sort -u)
TOTAL_BLOCKLIST=$(echo "$BLOCKLIST_DOMAINS" | wc -l)

if [ -f "$WHITELIST_FILE" ]; then
    WHITELIST_DOMAINS=$(grep -Rh '^local-' "$WHITELIST_FILE" | awk '{print $2}' | tr -d '"' | sort -u)
    TOTAL_WHITELIST=$(echo "$WHITELIST_DOMAINS" | wc -l)
else
    TOTAL_WHITELIST=0
fi

echo "✅ TOTAL domain blocklist : $TOTAL_BLOCKLIST"
echo "✅ TOTAL domain whitelist : $TOTAL_WHITELIST"
echo

#echo "📂 Jumlah domain per kategori:"
#echo "----------------------------------"
#for d in "$BLOCKLIST_DIR"/*; do
#    if [ -d "$d" ]; then
#        COUNT=$(grep -Rh '^local-' "$d" | awk '{print $2}' | tr -d '"' | sort -u | wc -l)
#        printf "%-12s : %s\n" "$(basename "$d")" "$COUNT"
#    fi
done
