server:
# Title: HaGeZi Roku Native Allowlist
# Description: Allow Roku-related domains
# Updated: 28/03/2026  1:38:30,11
local-zone: "Package size exceeded the configured limit of 150 MB. Try https://github.com/hagezi/dns-blocklists/tree/37522026.86.41994/domains/native.roku.txt instead.." always_transparent
