server:
# Title: HaGeZi Xiaomi Native Allowlist
# Description: Allow Xiaomi-related domains
# Updated: 08/04/2026  2:05:38,55
local-zone: "Package size exceeded the configured limit of 150 MB. Try https://github.com/hagezi/dns-blocklists/tree/37522026.97.38438/domains/native.xiaomi.txt instead.." always_transparent
