server:
# ALWAYS WHITELIST ---------------------------------------------------------------------------
local-zone: "lk21.team." always_transparent
local-zone: "lk21.de." always_transparent
local-zone: "lk21.party." always_transparent
local-zone: "tv10.lk21official.cc." always_transparent
local-zone: "lk21.de." always_transparent
local-zone: "lk21.party." always_transparent
local-zone: "tv.lk21official.love." always_transparent
local-zone: "playeriframe.sbs." always_transparent
local-zone: "config.teams.microsoft.com." always_transparent
